import Providers from "@skatemap/components/Providers";
import "@skatemap/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import type { PropsWithChildren } from "react";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export type RootLayoutProps = Readonly<
    PropsWithChildren<{
        modals: React.ReactNode;
    }>
>;

export default function RootLayout({ children, modals }: RootLayoutProps) {
    return (
        <html
            lang="en"
            className={`${GeistSans.variable}`}
            suppressHydrationWarning
        >
            <body>
                <Providers>
                    {children}
                    {modals}
                </Providers>
            </body>
        </html>
    );
}
